---
title: "Quiz week-2"
output: html_document
---


# 1
```{r, message=FALSE}
require(AppliedPredictiveModeling)
require(caret)
require(Hmisc)

data(AlzheimerDisease)


adData = data.frame(diagnosis, predictors)
trainIndex = createDataPartition(diagnosis,p=0.5,list=FALSE)
training = adData[trainIndex,]
testing = adData[-trainIndex,]
```

# 2
```{r}
data(concrete)
set.seed(1000)

inTrain = createDataPartition(mixtures$CompressiveStrength, p = 0.75)[[1]]
training = mixtures[ inTrain,]
testing = mixtures[-inTrain,]

train_cut <- apply(data.frame(mixtures), 2, function(x) {
  return(cut2(x, g=4))
})
train_cut <- data.frame(train_cut)
train_cut$CompressiveStrength <- mixtures$CompressiveStrength  # take original outcome variable


q <- ggplot(data=train_cut) +
  geom_point( aes(x=as.integer(rownames(train_cut)), y=CompressiveStrength) )
q

q <- ggplot(data=train_cut) +
  geom_point( aes(x=as.integer(rownames(train_cut)), y=CompressiveStrength, color=Age) )
q
```

# 3
```{r}
data(concrete)
set.seed(1000)

inTrain = createDataPartition(mixtures$CompressiveStrength, p = 0.75)[[1]]
training = mixtures[ inTrain,]
testing = mixtures[-inTrain,]

hist(mixtures$Superplasticizer, col='grey', breaks=30)
```


# 4
```{r, warning=F}
set.seed(3433)
adData = data.frame(diagnosis,predictors)

inTrain = createDataPartition(adData$diagnosis, p = 0.75)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

training <- training[, grepl('^IL', names(training))]  # all columns starting with 'IL'
logtrans <- log10(training)

#prComp <- prcomp(training)
preProc <- preProcess(training, method='pca', thres=0.8)
preProc
```
# 5
```{r}
set.seed(3433)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 0.75)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

training_compact <- training[, c(names(training)[grep("^IL",colnames(training))], 'diagnosis')]  # all columns starting with 'IL'
testing_compact <- testing[, c(names(testing)[grep("^IL",colnames(testing))], 'diagnosis')]

# PCA:
preProc <- preProcess(training_compact[, -ncol(training_compact)], method='pca', thres=0.8)
trainPC <- predict(preProc, training_compact[, -ncol(training_compact)])  # just the PCs explainging 80% of the variance an the outcome variable (could also be done manually)
trainPC <- data.frame(trainPC, training$diagnosis)  # add outcome variable

modelPC <- train(training.diagnosis ~ ., data= trainPC, method="glm")
#modelPC <- train(training_compact$diagnosis ~ ., method='glm', data=trainPC)

testPC <- predict(preProc, testing_compact[, -ncol(testing_compact)])  # all without last column
confusionMatrix(testing$diagnosis, predict(modelPC, testPC))

# regular (non-PCA):
model_regular <- train(diagnosis ~ ., data=training_compact, method='glm')
test_regular <- predict(model_regular, testing_compact[, -ncol(testing_compact)])
confusionMatrix(testing$diagnosis, test_regular)

```
#### ...from a forum:

https://github.com/topepo/caret/issues/521

```{r, eval=FALSE, echo=FALSE}
set.seed(3433)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]
# get the data with column names started with IL
New_training <- data.frame(training[,grep('^IL',names(training))],training$diagnosis)
New_testing <- data.frame(testing[,grep('^IL',names(testing))],testing$diagnosis)

# non-PCA
NotPCFit <- train(training.diagnosis ~.,data = New_training, method="glm")
NotPCTestPredict <- predict(NotPCFit, New_testing[, -13])
confusionMatrix(New_testing$testing.diagnosis, NotPCTestPredict)

# PCA
preProc <- preProcess(New_training[, -13],method="pca",thresh=.8)
trainPC <- predict(preProc, New_training[, -13])
testPC <- predict(preProc, New_testing[, -13])
# add the diagnosis into the trainPC data
trainPC <- data.frame(trainPC, training$diagnosis)

PCFit <- train(training.diagnosis ~.,data= trainPC, method="glm")
PCTestPredict <- predict(PCFit, testPC)
confusionMatrix(New_testing$testing.diagnosis, PCTestPredict)
```

